all:
  vars:
    ansible_user: wes
enzo:
  hosts:
    enzo.necrux.com
nas:
  hosts:
    truenas.necrux.com
windows:
  hosts:
    zen.necrux.com
  vars:
    ansible_user: ansible
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: ntlm
