---
- name: Upgrade apt packages.
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes
- name: Install base packages.
  ansible.builtin.package:
    name:
      - curl
      - tmux
      - git
      - pwgen
      - vim
    state: present
